In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "Date" : pd.date_range("2020-01-01", periods=20),
    "Product" : ["A" , "B" , "C" , "D"]*5,
    "Region" : ["east" , "west" , "north" , "south"]*5,
    "Sales" : np.random.randint(100 , 1000 , 20),
    "Units" : np.random.randint(10 , 100 , 20),
    "Rep" : ["John" , "Alice" , "Mary" , "Alice"]*5

}
df = pd.DataFrame(data)
df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = '0' + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2020-01-01       A   east    934     69   John  January      01
1  2020-01-02       B   west    569     19  Alice  January      01
2  2020-01-03       C  north    260     35   Mary  January      01
3  2020-01-04       D  south    874     53  Alice  January      01
4  2020-01-05       A   east    451     81   John  January      01
5  2020-01-06       B   west    246     57  Alice  January      01
6  2020-01-07       C  north    485     65   Mary  January      01
7  2020-01-08       D  south    870     79  Alice  January      01
8  2020-01-09       A   east    590     39   John  January      01
9  2020-01-10       B   west    367     69  Alice  January      01
10 2020-01-11       C  north    443     36   Mary  January      01
11 2020-01-12       D  south    987     40  Alice  January      01
12 2020-01-13       A   east    405     14   John  January      01
13 2020-01-14       B   west    948     15  Alice  January      01
14 2020-01-15       C  north    506     67   Mary  January      01
15 2020-01-16       D  south    833     70  Alice  January      01
16 2020-01-17       A   east    250     57   John  January      01
17 2020-01-18       B   west    715     96  Alice  January      01
18 2020-01-19       C  north    826     95   Mary  January      01
19 2020-01-20       D  south    452     91  Alice  January      01

In [7]:
pd.pivot_table(df , values="Sales", index="Region", columns="Product" , aggfunc=np.sum)

Product       A       B       C       D
Region
east     2630.0     NaN     NaN     NaN
north       NaN     NaN  2520.0     NaN
south       NaN     NaN     NaN  4016.0
west        NaN  2845.0     NaN     NaN

In [9]:
pivot2 = pd.pivot_table(df , values=["Sales" , "Units"] , index = "Region" , columns = "Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
east     526.0    NaN    NaN    NaN  52.0   NaN   NaN   NaN
north      NaN    NaN  504.0    NaN   NaN   NaN  59.6   NaN
south      NaN    NaN    NaN  803.2   NaN   NaN   NaN  66.6
west       NaN  569.0    NaN    NaN   NaN  51.2   NaN   NaN

CROSS TABS

In [11]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
east     5  0  0  0
north    0  0  5  0
south    0  0  0  5
west     0  5  0  0